// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwggeaadqlqbqhjzouyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Z2dlYWFkcWxxYnFoanpvdXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODg5NjAsImV4cCI6MjA1OTg2NDk2MH0.ioYw_sAldOQtAmus5s93iwfQOtFFZ_4p_JIJ5pGRUfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);